### ISSUE TITLE
Implementation: Implement Phase 3: Verification and Self-Healing

### ISSUE THREAD

**Issue by davidgibsonp** [davidgibsonp/open-specification-python#13]
### Objective

Agents can verify their own work comprehensively and recover from common failures without human intervention. After this phase, the human should never see a PR where CI is failing — agents self-correct before requesting review.

Currently agents can run `make pre-commit` to check their work, but when something fails the output isn’t optimized for agent consumption. Agents have to parse raw tool output to understand what went wrong. There’s also no structured guidance in AGENTS.md for how to diagnose and fix common failure categories.

After this phase, the verification loop is tight: agent runs verification → gets structured feedback on what failed and why → fixes the root cause → re-verifies → only opens PR when everything passes.

### Spec Reference

- `spec/ROADMAP.md` Phase 3: Verification and Self-Healing (all deliverables and success criteria)
- `spec/SPECIFICATION.md` Section 6: Verification Infrastructure (6.1 Makefile Targets, 6.2 Python Tooling Configuration, 6.3 Pre-commit Hooks)
- `spec/ARCHITECTURE.md`: Verification Infrastructure component
- `OPENSPEC.md` Section 5.3: The Self-Healing Protocol
- `OPENSPEC.md` Section 6: The Verification Contract

### Acceptance Criteria

- [ ] A `scripts/verify.sh` script exists that runs the full verification suite (lint, format check, type-check, test, coverage) and outputs structured, parseable results — each check clearly marked as PASS/FAIL with the relevant error output
- [ ] `make verify` target exists that wraps `scripts/verify.sh`
- [ ] Coverage threshold is enforced (default 80%, configurable in pyproject.toml) — `make test-cov` fails if coverage is below threshold
- [ ] AGENTS.md has a “Self-Healing Protocol” section with guidance on common failure categories and how to fix them:
  - Ruff lint errors: what the error codes mean, how to auto-fix vs. manual fix
  - Mypy type errors: common causes (missing type hints, incompatible types, missing imports)
  - Test failures: how to read pytest output, how to isolate failing tests
  - Import errors: how to diagnose circular imports, missing `__init__.py`, wrong package paths
  - Pre-commit failures: how to re-run specific hooks
- [ ] CI workflow (`.github/workflows/pre-commit.yml`) outputs structured failure information — not just a red X, but the specific check that failed and the relevant error lines, readable from the Actions log
- [ ] The verification script returns a non-zero exit code on any failure (so agents can programmatically detect failure)
- [ ] Verification results are deterministic — running twice with the same code produces the same result
- [ ] All existing tests still pass after changes
- [ ] All verification steps pass (`make pre-commit`)

### Context

This is Phase 3 of the roadmap. It can be built independently of Phase 2 (Bootstrap Automation) — both depend on Phase 1 but not on each other.

The current state:

- `make pre-commit` runs all hooks but output is raw pre-commit format
- `make test-cov` shows coverage but doesn’t enforce a threshold
- `make lint`, `make format`, `make type-check` exist individually
- There’s no unified verification script with structured output
- AGENTS.md has mandatory rules but no self-healing guidance
- CI just runs pre-commit and shows pass/fail without structured error extraction

Key design guidance from the spec: `scripts/verify.sh` should output something an agent can parse programmatically — not a fancy reporting format, just clear PASS/FAIL per check with the error output when something fails. Think of it as the agent running `scripts/verify.sh`, scanning the output for any FAIL lines, reading the error details for those checks, and knowing exactly what to fix.

Keep it simple. The goal is structured feedback, not a dashboard. A bash script that runs each check sequentially and reports results is sufficient. Don’t over-engineer this.

Review `docs/learnings/` for any relevant patterns from previous issues before starting implementation.

### Roadmap Phase

None
